package aplikasiRentalMobil.apk;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Administrator
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public home(String string) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenuItem();
        menuData = new javax.swing.JMenu();
        menuDataMobil = new javax.swing.JMenuItem();
        menuDataSopir = new javax.swing.JMenuItem();
        menuDataPelanggan = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuPemesanan = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        laporanMobil = new javax.swing.JMenuItem();
        laporanSopir = new javax.swing.JMenuItem();
        laporanPelanggan = new javax.swing.JMenuItem();
        laporanTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("SELAMAT DATANG DI APLIKASI RENTAL MOBIL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasiRentalMobil/apk/1mobil.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuHome.setText("Home");

        menuKeluar.setText("Keluar");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menuHome.add(menuKeluar);

        jMenuBar1.add(menuHome);

        menuData.setText("Data Master");

        menuDataMobil.setText("Data Mobil");
        menuDataMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataMobilActionPerformed(evt);
            }
        });
        menuData.add(menuDataMobil);

        menuDataSopir.setText("Data Sopir");
        menuDataSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataSopirActionPerformed(evt);
            }
        });
        menuData.add(menuDataSopir);

        menuDataPelanggan.setText("Data Pelanggan");
        menuDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataPelangganActionPerformed(evt);
            }
        });
        menuData.add(menuDataPelanggan);

        jMenuBar1.add(menuData);

        menuTransaksi.setText("Transaksi");

        menuPemesanan.setText("Pemesanan");
        menuPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPemesananActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPemesanan);

        jMenuBar1.add(menuTransaksi);

        menuLaporan.setText("Laporan");

        laporanMobil.setText("Laporan Data Mobil");
        laporanMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanMobilActionPerformed(evt);
            }
        });
        menuLaporan.add(laporanMobil);

        laporanSopir.setText("Laporan Data Sopir");
        laporanSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanSopirActionPerformed(evt);
            }
        });
        menuLaporan.add(laporanSopir);

        laporanPelanggan.setText("Laporan Data Pelanggan");
        laporanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanPelangganActionPerformed(evt);
            }
        });
        menuLaporan.add(laporanPelanggan);

        laporanTransaksi.setText("Laporan Transaksi");
        laporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanTransaksiActionPerformed(evt);
            }
        });
        menuLaporan.add(laporanTransaksi);

        jMenuBar1.add(menuLaporan);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDataMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataMobilActionPerformed
        // TODO add your handling code here:
        mobil m = new mobil();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuDataMobilActionPerformed

    private void menuDataSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataSopirActionPerformed
        // TODO add your handling code here:
        sopir s = new sopir();
        s.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuDataSopirActionPerformed

    private void menuDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataPelangganActionPerformed
        // TODO add your handling code here:
        pelanggan p = new pelanggan();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuDataPelangganActionPerformed

    private void menuPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPemesananActionPerformed
        // TODO add your handling code here:
        pemesanan pm = new pemesanan();
        pm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPemesananActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void laporanMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanMobilActionPerformed
        // TODO add your handling code here:
        try{
            JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("reportMobil.jasper"), null, conek.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanMobilActionPerformed

    private void laporanSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanSopirActionPerformed
        // TODO add your handling code here:
        try{
            JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("reportSopir.jasper"), null, conek.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanSopirActionPerformed

    private void laporanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanPelangganActionPerformed
        // TODO add your handling code here:
        try{
            JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("reportPelanggan.jasper"), null, conek.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanPelangganActionPerformed

    private void laporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanTransaksiActionPerformed
        // TODO add your handling code here:
        try{
            JasperPrint jp = JasperFillManager.fillReport(
                getClass().getResourceAsStream("reportPemesanan.jasper"), null, conek.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_laporanTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem laporanMobil;
    private javax.swing.JMenuItem laporanPelanggan;
    private javax.swing.JMenuItem laporanSopir;
    private javax.swing.JMenuItem laporanTransaksi;
    private javax.swing.JMenu menuData;
    private javax.swing.JMenuItem menuDataMobil;
    private javax.swing.JMenuItem menuDataPelanggan;
    private javax.swing.JMenuItem menuDataSopir;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuPemesanan;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
